version: '3'
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "7003:3000"
    depends_on:
      - mongo
    command: npm start -- --port 3000
    working_dir: /TheRealDevOps/client
    volumes:
      - ./client:/TheRealDevOps/client
    environment:
      - NODE_ENV=development
    networks:
      - thebobs  # Conectar a la red "thebobs"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - thebobs  # Conectar a la red "thebobs"

networks:
  thebobs:  # Definir la red "thebobs"
    driver: bridge
