name: Deploy to Skynet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        cd api
        npm install
        cd ../client
        npm install

    - name: Build Client
      run: |
        cd client
        npm run build
        cd ..

    - name: Deploy to Skynet
      uses: appleboy/ssh-action
      with:
        host: ${{ secrets.PRIVATE_SERVER_HOST }}:44  ## Agregar PRIVATE_SERVER_HOST con el puerto 44
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p /TheRealDevOps
          cd /TheRealDevOps
          git pull origin master
