name: Deploy to Skynet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        cd api
        npm install
        cd ../client
        npm install

    - name: Build Client
      run: |
        cd client
        npm run build
        cd ..

    - name: Deploy to Skynet
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.PRIVATE_SERVER_HOST }} -p 44 "mkdir -p /TheRealDevOps && cd /TheRealDevOps && git pull origin master"
  
