name: Deploy to Skynet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        cd api
        npm install
        cd ../client
        npm install

    - name: Build Client
      run: |
        cd client
        npm run build
        cd ..

    #- name: Deploy to Skynet
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install -y sshpass
    #    sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.PRIVATE_SERVER_HOST }} -p 44 "mkdir -p /TheRealDevOps && cd /TheRealDevOps && git pull origin master"
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm install
      - name: Run Tests
        run: |
          npm test
  build_and_upload:
      runs-on: ubuntu-20.04
      needs:
        - test
      steps:
        - name: Checkout git
          uses: actions/checkout@v4
        - name: Install Dependencies
          run: npm install
        - name: Build Application
          run: npm run build
        - name: QEMU
          uses: docker/setup-qemu-action@v3
        - name: Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Push image to dockerhub
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: nachin7u7/proyecto-final-thebobs:latest
