name: Deploy to Skynet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        (cd .\api\ && npm install) &
        (cd .\client\ && npm install) &
        wait
    - name: Build
      run: |
        (cd client && npm start) &
        (cd api && npm start) &
        wait

    - name: Deploy to Skynet
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.PRIVATE_SERVER_HOST }}:44 ## agregar PRIVATE_SERVER_HOST
        username: ${{ secrets.SSH_USERNAME }}       ## agregar SSH_USERNAME
        key: ${{ secrets.SSH_PRIVATE_KEY }}         ## agregar SSH_PRIVATE_KEY
        script: |
          # cd /ruta/a/tu/aplicacion
          git pull origin master
